scan:
  anonymize: false
  dry_run: false
  exclude_directories:
  - .git
  - node_modules
  include_patterns:
  - '*.py'
  - '*.js'
  - '*.java'
  - '*.c'
  - '*.cpp'
  - '*.cs'
  - '*.rb'
  - '*.go'
  - '*.php'
  rule_file: rsa_rules.yml
  scan_root: C:\Users\
  verbose: true
