# config.yml
encryption:
  algorithm: "hybrid RSA+Kyber"   # Use our recommended PQC alternative
  key_size: 3072                  # A secure key size
logging:
  level: "DEBUG"
  hash: "SHA-256"                 # Secure hash function

scan:
  scan_root: "/path/to/scan"      # Update this to the directory you wish to scan
  include_patterns:
    - "*.py"
    - "*.js"
    - "*.json"
    - "*.cfg"
    - "*.ini"
    - "*.yml"
  exclude_directories:
    - ".git"
    - "node_modules"
    - "/proc"
    - "/sys"
    - "C:\\Windows"
  dry_run: false                  # Set to true for a test run that logs files only
  verbose: true                   # Print detailed progress messages
